### PR TITLE
Use base package

### PR DESCRIPTION
**Pull request by ericpre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ericpre** [comment]
Running the kikuchypy test suite fails because of the reason mentioned in https://github.com/hyperspy/hyperspy-extensions-list/pull/5 (https://github.com/pyxem/kikuchipy/issues/251).

@hakonanes, if you do a release soon, I guess it is worth waiting for it and the changes of this PR can added when the recipe is updated?

**Comment by hakonanes** [comment]
> Running the kikuchypy test suite fails because of the reason mentioned in [hyperspy/hyperspy-extensions-list#5](https://github.com/hyperspy/hyperspy-extensions-list/pull/5) ([pyxem/kikuchipy#251](https://github.com/pyxem/kikuchipy/issues/251)).
> 
> @hakonanes, if you do a release soon, I guess it is worth waiting for it and the changes of this PR can added when the recipe is updated?

Yes, let's wait for that. Thanks a lot!

**Comment by hakonanes** [comment]
Suggested changes were included in #8. Thanks, @ericpre!

**Comment by ericpre** [comment]
You forgot to remove the `recipe/yum_requirements.txt` in both #8 and #9.

**Comment by hakonanes** [comment]
I didn't realise that that was a change you made. Why was it necessary to remove it?

**Comment by ericpre** [comment]
The right question is: is it necessary to have something which is not necessary?

**Comment by hakonanes** [comment]
I agree, it was initially added by the regro bot, which I usually don't question. I'll remove the line in a new 0.3.1 conda-forge release PR.

**Comment by hakonanes** [comment]
The mentioned file is removed in #10

**Pull request closed without merging**
